version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=locahost
      - MONGODB_URL=mongo
    networks:
      - backend
      - frontend

  mongo:
    image: mongo:6.0
    ports:
      - "27017"
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - frontend

networks:
  backend:
  frontend:
