version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=locahost
      - MONGODB_URL=mongo
    networks:
      - backend
  mongo:
    image: mongo:6.0
    ports:
      - "27017"
    networks:
      - backend

networks:
  backend:
  frontend:
