name: Build Images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
env:
  IMAGE_PREFIX: "${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}"
  IMAGE_SUFFIX: "${{ github.event_name }}-${{ env.GITHUB_SHA }}"
  
jobs:          
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3
        
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Backend
        working-directory: backend
        env:
          IMAGE_NAME: ${{ env.IMAGE_PREFIX }}-backend:0.0.1-${{ env.IMAGE_SUFFIX }}
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}
              
      - name: Build Frontend
        working-directory: frontend
        env:
          IMAGE_NAME: ${{ env.IMAGE_PREFIX }}-frontend:0.0.1-${{ env.IMAGE_SUFFIX }}
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}
       
