name: Build Images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
env:
  IMAGE_PREFIX: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
  
jobs:
  setup-env:
    name: Setup Environments
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Prefix for pull_request event
        if: github.event_name === "pull_request"
        env:
          IMAGE_TAG_SUFFIX: ${{ github.event.number }}
          
      - name: Set Prefix for push event
        if: github.event_name === "push"
        env:
          IMAGE_TAG_SUFFIX: ${{ env.GITHUB_SHA }}
          
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [setup-env]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3
        
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build Backend
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}
        working-directory: backend
        env:
          IMAGE_NAME: ${{ env.IMAGE_PREFIX }}-backend:0.0.1-${{ github.setup-env.steps.env.IMAGE_TAG_SUFFIX }}
              
      - name: Build Frontend
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}
        working-directory: frontend
        env:
          IMAGE_NAME: ${{ env.IMAGE_PREFIX }}-frontend:0.0.1-${{ github.setup-env.steps.env.IMAGE_TAG_SUFFIX }}
