on:
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
    inputs: 
      build_number:
        description: 'Build Number for Image'
        required: true
        type: string

env:
  IMAGE_PREFIX: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
  
jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3
        
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
      - name: Build Backend
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}
        working-directory: backend
        env:
          IMAGE_NAME: ${{ env.IMAGE_PREFIX }}-backend:0.0.1-${{ github.event.number }}
              
      - name: Build Frontend
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}
        working-directory: frontend
        env:
          IMAGE_NAME: ${{ env.IMAGE_PREFIX }}-frontend:0.0.1-${{ github.event.number }}
