on:
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
    inputs: 
      build_number:
        description: 'Build Number for Image'
        required: true
        type: string
        
jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3
        
      - name: Build Backend
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
