name: Build Images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
env:
  IMAGE_PREFIX: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
  IMAGE_TAG_SUFFIX: ${{ github.event_name }}-${{ env.GITHUB_SHA }}
  
jobs:          
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3
        
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

