on:
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
    inputs: 
      build_number:
        description: 'Build Number for Image'
        required: true
        type: string
        
jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend/
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3
        
      - name: Build Backend
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:0.0.1-${{ github.event.number }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t $env.IMAGE_NAME .
          docker push $env.IMAGE_NAME
