on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  labeller:
    name: Labeller Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Labeler
        uses: actions/labeler@v4.1.0
        with:
          dot: true
          
  assignee:
    name: Assignee Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Update
        run: |
          curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/issues/${{ github.event.number }}/assignees \
            -d '{"assignees":["${{ github.event.pull_request.user.login }}"]}'
